apiVersion: v1
kind: Service
metadata:
  name: {{ include "poibot.fullname" . }}
  labels:
{{ include "poibot.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.sslport }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "poibot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
