apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: letsencrypt
  labels:
{{ include "test.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "test.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
