apiVersion: v1
kind: Service
metadata:
  name: {{ include "motherbot.fullname" . }}
  labels:
{{ include "motherbot.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.sslport }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "motherbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
